services:
  selene:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'selene-gobaith-server:local'
    ports:
      - '8147:8147'
    volumes:
      - selene_save:/app/save

volumes:
  selene_save:
